## Arrays

### Vectors

A **vector** is a one-dimensional array that stores a sequence of values. We can construct a vector using square brackets, separating elements by commas.

In [16]:
@show x = [];                      # empty vector
@show x = trues(3);                # Boolean vector containing three trues
@show x = ones(3);                 # vector of three ones
@show x = zeros(3);                # vector of three zeros
@show x = rand(3);                 # vector of three random numbers between 0 and 1
@show x = [3, 1, 4];               # vector of integers
@show x = [3.1415, 1.618, 2.7182]; # vector of floats

x = [] = Any[]
x = trues(3) = Bool[1, 1, 1]
x = ones(3) = [1.0, 1.0, 1.0]
x = zeros(3) = [0.0, 0.0, 0.0]
x = rand(3) = [0.36529204949937544, 0.9807067111539537, 0.8873488855823283]
x = [3, 1, 4] = [3, 1, 4]
x = [3.1415, 1.618, 2.7182] = [3.1415, 1.618, 2.7182]


An **array comprehension** can be used to create vectors. Below, we use the `print` function so that the output is printed horizontally.

In [17]:
print([sin(x) for x = 1:5]) # You'll get to know what `for`` and `1:5`` means later.

[0.8414709848078965, 0.9092974268256817, 0.1411200080598672, -0.7568024953079282, -0.9589242746631385]

We can inspect the type of vectors.

In [18]:
typeof([3, 1, 4])               # 1-dimensional array of Int64s

Vector{Int64} (alias for Array{Int64, 1})

In [19]:
typeof([3.1415, 1.618, 2.7182]) # 1-dimensional array of Float64s

Vector{Float64} (alias for Array{Float64, 1})

### Referencing Items

We index into vectors using square brackets.

In [20]:
x[1] # Unlike Python, first element is indexed by 1.

3.1415

In [21]:
x[3] # third element of x

2.7182

In [22]:
x[end] # use `end` to reference the end of the array

2.7182

In [23]:
x[end - 1] # this returns the second to last element

1.618

We can pull out a range of elements from an array. Ranges are specified using a colon notation.

In [24]:
x = [1, 1, 2, 3, 5, 8, 13];

In [25]:
print(x[1:3]) # pull out the first three elements

[1, 1, 2]

In [26]:
print(x[1:2:end]) # pull out every other element; note that x[1:2:] raises the ParseError: missing last argument in range expression

[1, 2, 5, 13]

In [27]:
print(x[end:-1:1]) # pull out all the elements in reverse order

[13, 8, 5, 3, 2, 1, 1]

We can perform a variety of different operations on arrays. The exclamation mark at the end of function names is often used to indicate that the function mutates (i.e., changes) the input.

In [28]:
print([x, x]) # concatenation

[[1, 1, 2, 3, 5, 8, 13], [1, 1, 2, 3, 5, 8, 13]]

In [29]:
length(x)

7

In [30]:
print(push!(x, -1)) # add an element to the end.

[1, 1, 2, 3, 5, 8, 13, -1]

In [31]:
pop!(x) # remove an element from the end.
print(x)

[1, 1, 2, 3, 5, 8, 13]

In [32]:
print(append!(x, [2, 3])) # append y to the end of x

[1, 1, 2, 3, 5, 8, 13, 2, 3]

In [33]:
print(sort!(x)) # sort the elements in the vector.

[1, 1, 2, 2, 3, 3, 5, 8, 13]

In [34]:
x[1] = 2; # change the first element to 2.
print(x)

[2, 1, 2, 2, 3, 3, 5, 8, 13]

In [35]:
x = [1, 2];
y = [3, 4];

In [36]:
print(x + y) # add vectors

[4, 6]

In [37]:
print(3x - [1, 2]) # multiply by a scalar and substract.

[2, 4]

In [38]:
using LinearAlgebra
@show dot(x, y); # dot product
@show x ⋅ y;       # dot product using unicode character

dot(x, y) = 11
x ⋅ y = 11


It is often useful to apply various functions elementwise to vectors.

In [39]:
print(x .* y) # elementwise multiplication

[3, 8]

In [40]:
print(x .^ 2) # elementwise squaring

[1, 4]

In [41]:
print(sin.(x)) # elementwise application of sin

[0.8414709848078965, 0.9092974268256817]

In [42]:
print(sqrt.(x)) # elementwise application of sqrt

[1.0, 1.4142135623730951]

### Matrices

A **matrix** is a two-dimensional array. Like a vector, it is constructed using square brackets. We use spaces to delimit elements in the same row and semicolons to delimit rows. We can also index into the matrix and output submatrices using ranges.

In [43]:
X = [1 2 3; 4 5 6; 7 8 9; 10 11 12];

In [44]:
typeof(X) # a 2-dimensional array of Int64s

Matrix{Int64} (alias for Array{Int64, 2})

In [45]:
X[2] # second element using column-major ordering

4

In [46]:
print(X[1, :]) # extract the first row

[1, 2, 3]

In [47]:
print(X[:, 2]) # extract the second column

[2, 5, 8, 11]

In [48]:
print(X[:, 1:2]) # extract the first two columns

[1 2; 4 5; 7 8; 10 11]

In [49]:
print(X[1:2, 1:2]) # extract a 2×2 matrix from the top left of X

[1 2; 4 5]

We can also construct a variety of special matrices and use array comprehensions:

In [ ]:
Matrix(1.0I, 3, 3) # 3×3 identity matrix

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [52]:
Matrix(Diagonal([3, 2, 1])) # 3×3 diagonal matrix with 3, 2, 1 on diagonal

3×3 Matrix{Int64}:
 3  0  0
 0  2  0
 0  0  1

In [54]:
rand(3, 2) # 3×2 random matrix

3×2 Matrix{Float64}:
 0.774013  0.943015
 0.40806   0.381623
 0.21831   0.572548

In [55]:
zeros(3, 2) # 3×2 matrix of zeros

3×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0
 0.0  0.0

In [57]:
[sin(x+y) for x = 1:3, y = 1:2] # array comprehension

3×2 Matrix{Float64}:
  0.909297   0.14112
  0.14112   -0.756802
 -0.756802  -0.958924

Matrix operations include the following:

In [60]:
X' # complex conjugate transpose (adjoint operator)

3×4 adjoint(::Matrix{Int64}) with eltype Int64:
 1  4  7  10
 2  5  8  11
 3  6  9  12

In [63]:
3X .+ 2 # multiplying by scalar and adding scalar

4×3 Matrix{Int64}:
  5   8  11
 14  17  20
 23  26  29
 32  35  38

In [67]:
X = [1 3; 3 1]  # Create an invertible matrix
@show inv(X);   # matrix inverse
@show det(X);   # determinant

inv(X) = [-0.125 0.375; 0.375 -0.125]
det(X) = -8.0


In [70]:
@show [X X];  # horizontal concatenation
@show [X; X]; # vertical concatenation

[X X] = [1 3 1 3; 3 1 3 1]
[X; X] = [1 3; 3 1; 1 3; 3 1]


In [72]:
sin.(X) # elementwise application of sin

2×2 Matrix{Float64}:
 0.841471  0.14112
 0.14112   0.841471

## Tuples

A **tuple** is an ordered list of values, potentially of different types. They are constructed with parantheses. They are similar to arrays, but they cannot be mutated.

In [75]:
x = (1,) # a single element tuple indicated by the trailing comma
typeof(x)

Tuple{Int64}

In [76]:
x = (1, 0, [1, 2], 2.5029, 4.6692) # third element is a vector

(1, 0, [1, 2], 2.5029, 4.6692)

In [77]:
x[2]

0

In [78]:
x[end]

4.6692

In [79]:
x[4:end]

(2.5029, 4.6692)

In [80]:
length(x)

5

In [83]:
(2, 3, 4) .+ (1, 2, 3)

(3, 5, 7)

In [11]:
x = ("foo", "bar");
y = ("foo", 2);

In [13]:
typeof(x), typeof(y)

(Tuple{String, String}, Tuple{String, Int64})

In [5]:
x = "foo", 1 # Tuples can be constructed with or without parentheses.

("foo", 1)

In [19]:
function f()
    return "foo", 1
end;

In [21]:
f()

("foo", 1)

In [6]:
# Tuples can also be unpacked directly into variables.
word, val = ("foo", 1);
println("word = $word, val = $val")

word = foo, val = 1


In [15]:
# Tuples can be created with a hanging `,` - this is useful to create a tuple with one element.
x = ("foo");
y = ("foo", );

println("Type of x: $(typeof(x))")
println("Type of y: $(typeof(y))")

Type of x: String
Type of y: Tuple{String}


## Referencing Items

In [16]:
x = [10, 20, 30, 40];

In [17]:
x[end]

40

In [18]:
x[end - 1]

30

In [19]:
# slice notation
x[1:3]

3-element Vector{Int64}:
 10
 20
 30

In [20]:
x[2:end]

3-element Vector{Int64}:
 20
 30
 40

In [22]:
# The same slice notation works on strings
str = "foobar";
str[3:end]

"obar"

## Dictionaries

A **dictionary** is a collection of key-value pairs. Key-value pairs are indicated with a double arrow operator. We can index into a dictionary using square brackets as with arrays and tuples.

In [88]:
x = Dict() # empty dictionary
println(x)

x[3] = 4;  # Associate value 4 with key 3
print(x)

Dict{Any, Any}()
Dict{Any, Any}(3 => 4)

In [89]:
x = Dict(3=>4, 5=>1) # Create a dictionary with two key-value pairs.

Dict{Int64, Int64} with 2 entries:
  5 => 1
  3 => 4

In [92]:
x[5] # return value associated with key 5

1

In [93]:
haskey(x, 3) # check whether dictionary has key 3

true

In [94]:
haskey(x, 4) # check whether dictionary has key 4

false

In [23]:
d = Dict("name" => "Frodo", "age" => 33)

Dict{String, Any} with 2 entries:
  "name" => "Frodo"
  "age"  => 33

In [24]:
d["age"]

33

In [25]:
keys(d)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "name"
  "age"

In [26]:
values(d)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "Frodo"
  33

## Composite Types

A **composite type** is a collection of named fields. By default, an instance of a composite type is immutable (i.e., it cannot change). We use the `struct` keyword and then give the new type a name and list the names of the fields.

In [95]:
struct A
    a
    b
end

Adding the keyword `mutable` makes it so that an instance can change.

In [96]:
mutable struct B
    a
    b
end

Composite types are constructed using parantheses, between which we pass in values for the different fields. For example,

In [97]:
x = A(1.414, 1.732)

A(1.414, 1.732)

The double-colon operator can be used to annotate the types for fields.

In [99]:
struct C
    a::Int64
    b::Float64
end

This annotation requires that we pass in an `Int64` for the first field and a `Float64` for the second field. For compactness, this text does not use type annotations, but it is at the expense of performance. Type annotations allow Julia to improve runtime performance because the compiler can optimize the underlying code for specific types.

## Abstract Types

So far we have discussed *concrete types*, which are types that we can construct. However, concrete types are only part of the type hierarchy. There are also *abstract types*, which are supertypes of concrete types and other abstract types.

We can explore the type hierarchy of the `Float64` type shown in the following figure using the `supertype` and `subtypes` functions.

```markdown
Any
+-- Number
⋮   +-- Real
    ⋮   +-- AbstractFloat
        ⋮   +-- Float64
            +-- Float32
            +-- Float16
            +-- BigFloat
```

In [6]:
@show supertype(Float64);
@show supertype(AbstractFloat);
@show supertype(Real);
@show supertype(Number);
@show supertype(Any); # Any is at the top of the hierarchy

supertype(Float64) = AbstractFloat
supertype(AbstractFloat) = Real
supertype(Real) = Number
supertype(Number) = Any
supertype(Any) = Any


In [8]:
@show subtypes(AbstractFloat); # different types of AbstractFloats
@show subtypes(Float64);       # Float64 does not have any subtypes.

subtypes(AbstractFloat) = Any[BigFloat, Float16, Float32, Float64]
subtypes(Float64) = Type[]


We can define our own abstract types.

In [10]:
abstract type D end
abstract type E <: D end # E is an abstract subtype of C
struct F <: E            # E is a composite type tyat is a subtype of E
    a
end

## Parametric Types

Julia supports *parametric types*, which are types that take parameters. We have already seen a parametric type with our dictionary example.

In [11]:
x = Dict(3=>4, 5=>1)

Dict{Int64, Int64} with 2 entries:
  5 => 1
  3 => 4

This constructs a `Dict{Int64, Int64}`. The parameters to the parameter type are listed within braces and delimited by commas. For the dictionary type, the first parameter specifies the key type, and the second parameter specifies the value type. Julia was able to infer this based on the input, but we could have specified it explicitly.

In [12]:
x = Dict{Int64, Int64}(3=>4, 5=>1)

Dict{Int64, Int64} with 2 entries:
  5 => 1
  3 => 4

It is possible to define our own parametric types, but we do not do that in this note. (Wait for future updates!)